// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn08IxmepHsmVIoB0hO_ZYwjh0kqoKpJY',
    appId: '1:701283127731:web:9d5d5d81b341697d84bbc6',
    messagingSenderId: '701283127731',
    projectId: 'tea-midterm',
    authDomain: 'tea-midterm.firebaseapp.com',
    storageBucket: 'tea-midterm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvat2f5mTglwsuVcftfRFyu2y4kk6nftw',
    appId: '1:701283127731:android:e943b5b91f26862084bbc6',
    messagingSenderId: '701283127731',
    projectId: 'tea-midterm',
    storageBucket: 'tea-midterm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0l-rH-q6hTV34VluGNEwrBhTmQEWO4as',
    appId: '1:701283127731:ios:18a236afeb66e91b84bbc6',
    messagingSenderId: '701283127731',
    projectId: 'tea-midterm',
    storageBucket: 'tea-midterm.appspot.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0l-rH-q6hTV34VluGNEwrBhTmQEWO4as',
    appId: '1:701283127731:ios:18a236afeb66e91b84bbc6',
    messagingSenderId: '701283127731',
    projectId: 'tea-midterm',
    storageBucket: 'tea-midterm.appspot.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn08IxmepHsmVIoB0hO_ZYwjh0kqoKpJY',
    appId: '1:701283127731:web:3eb7246398ef3f4684bbc6',
    messagingSenderId: '701283127731',
    projectId: 'tea-midterm',
    authDomain: 'tea-midterm.firebaseapp.com',
    storageBucket: 'tea-midterm.appspot.com',
  );
}
